[_]
schema-version = "0.2"

[io.buildpacks]
builder = "paketobuildpacks/builder-jammy-full"

group = [
  {uri = "gcr.io/paketo-buildpacks/php"},
  {uri = "./.buildpacks/bun"},
  {uri = "./.buildpacks/dynamic-codebase"},
]

build.env = [
  {name = "BPE_DEFAULT_PORT", value = "8080"},
  {name = "BP_PHP_SERVER", value = "httpd"},
  {name = "BP_PHP_WEB_DIR", value = "php-app/web"},
  {name = "BP_DYNAMIC_CODEBASE_DIRS", value = "php-app php-app/web"},
]
